version: '3.8'

services:
  # 1. Base de Datos Centralizada
  postgres_db:
    image: postgres:15-alpine
    container_name: parking_db
    restart: always
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: parking_master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dev -d parking_master"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Microservicio Auth
  ms-user-auth:
    build: ./ms-user-auth
    container_name: ms-user-auth
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=postgres_db
      - DB_NAME=parking_master
      - DB_USER=user_dev
      - DB_PASS=secret_password
      - JWT_SECRET=una_clave_secreta_muy_larga_y_segura_2025
    depends_on:
      postgres_db:
        condition: service_healthy

  # 3. Microservicio Core Branch
  ms-core-branch:
    build: ./ms-core-branch
    container_name: ms-core-branch
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=postgres_db
      - DB_NAME=parking_master
      - DB_USER=user_dev
      - DB_PASS=secret_password
      - JWT_SECRET=una_clave_secreta_muy_larga_y_segura_2025
      - AUTH_SERVICE_URL=http://ms-user-auth:3002/api/v1/auth
    depends_on:
      postgres_db:
        condition: service_healthy
      ms-user-auth:
        condition: service_started

  # 4. Microservicio Tariff
  ms-tariff-config:
    build: ./ms-tariff-config
    container_name: ms-tariff-config
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DB_HOST=postgres_db
      - DB_NAME=parking_master
      - DB_USER=user_dev
      - DB_PASS=secret_password
      - JWT_SECRET=una_clave_secreta_muy_larga_y_segura_2025
      - AUTH_SERVICE_URL=http://ms-user-auth:3002/api/v1/auth
    depends_on:
      postgres_db:
        condition: service_healthy
      ms-user-auth:
        condition: service_started

  # 5. Microservicio Operation Ticket
  ms-operation-ticket:
    build: ./ms-operation-ticket
    container_name: ms-operation-ticket
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DB_HOST=postgres_db
      - DB_NAME=parking_master
      - DB_USER=user_dev
      - DB_PASS=secret_password
      - JWT_SECRET=una_clave_secreta_muy_larga_y_segura_2025
      - AUTH_SERVICE_URL=http://ms-user-auth:3002/api/v1/auth
      - TARIFF_SERVICE_URL=http://ms-tariff-config:3003/api/v1/tariffs
      - BRANCH_SERVICE_URL=http://ms-core-branch:3001/api/v1/branches
      - FINANCIAL_SERVICE_URL=http://ms-financial-cash:3005/api/v1/financial
    depends_on:
      postgres_db:
        condition: service_healthy
      ms-user-auth:
        condition: service_started
      ms-tariff-config:
        condition: service_started

  # 6. Microservicio Financial Cash
  ms-financial-cash:
    build: ./ms-financial-cash
    container_name: ms-financial-cash
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DB_HOST=postgres_db
      - DB_NAME=parking_master
      - DB_USER=user_dev
      - DB_PASS=secret_password
      - JWT_SECRET=una_clave_secreta_muy_larga_y_segura_2025
      - AUTH_SERVICE_URL=http://ms-user-auth:3002/api/v1/auth
      - TICKET_SERVICE_URL=http://ms-operation-ticket:3004/api/v1/tickets
    depends_on:
      postgres_db:
        condition: service_healthy
      ms-operation-ticket:
        condition: service_started

  # 7. Microservicio Reporting
  ms-reporting:
    build: ./ms-reporting
    container_name: ms-reporting
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - DB_HOST=postgres_db
      - DB_NAME=parking_master
      - DB_USER=user_dev
      - DB_PASS=secret_password
      - JWT_SECRET=una_clave_secreta_muy_larga_y_segura_2025
      - AUTH_SERVICE_URL=http://ms-user-auth:3002/api/v1/auth
      - FINANCIAL_SERVICE_URL=http://ms-financial-cash:3005/api/v1/financial
    depends_on:
      postgres_db:
        condition: service_healthy
      ms-user-auth:
        condition: service_started

  # 8. API Gateway (Nginx)
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ms-user-auth
      - ms-core-branch
      - ms-tariff-config
      - ms-operation-ticket
      - ms-financial-cash
      - ms-reporting

volumes:
  postgres_data: