upstream auth_server {
    server ms-user-auth:3002; 
}
server {
    listen 80;

    

   
    location /api/v1/auth {
        proxy_pass http://ms-user-auth:3002;
    }

    
    location /api/v1/branches {
        proxy_pass http://ms-core-branch:3001;
    }

    
    location /api/v1/tariffs {
        proxy_pass http://ms-tariff-config:3003;
    }

    
    location /api/v1/tickets {
        proxy_pass http://ms-operation-ticket:3004;
    }

    
    location /api/v1/financial {
        proxy_pass http://ms-financial-cash:3005;
    }

    
    location /api/v1/reports {
        proxy_pass http://ms-reporting:3006;
    }
}