upstream auth_server {
    server ms-user-auth:3002; # Debe coincidir con el nombre en docker-compose
}
server {
    listen 8080;

    # Microservicio Auth (Puerto 3002)
    location /api/v1/auth {
        proxy_pass http://ms-user-auth:3002;
    }

    # Microservicio Core Branch (Puerto 3001)
    location /api/v1/branches {
        proxy_pass http://ms-core-branch:3001;
    }

    # Microservicio Tariff (Puerto 3003)
    location /api/v1/tariffs {
        proxy_pass http://ms-tariff-config:3003;
    }

    # Microservicio Operation Ticket (Puerto 3004)
    location /api/v1/tickets {
        proxy_pass http://ms-operation-ticket:3004;
    }

    # Microservicio Financial Cash (Puerto 3005)
    location /api/v1/financial {
        proxy_pass http://ms-financial-cash:3005;
    }

    # Microservicio Reporting (Puerto 3006)
    location /api/v1/reports {
        proxy_pass http://ms-reporting:3006;
    }
}